### ISSUE TITLE
Add an image of the product in the readme.md 

### ISSUE THREAD

**Issue by AadityaMunjal** [ItsLegendaryCode/PyElite#2]
An image would attract more people as it is tedious to clone the repo and then run the code to see what you've made.

**Comment by ItsLegendaryCode** [comment]
Yes, I will be considering the enrichment of the GitHub repository, but for now my goal is to work on this project in the code level. As you may have noticed, there are quite a few bugs to fix and I am so thankful to have your advice. (Please understand that when I say this, I am just prioritizing what I need to fix. Thanks so much for your contribution in advising me :)
