### ISSUE TITLE
Columns and Row THing not coutning correctly

### ISSUE THREAD

**Issue by LiamAmsdorf** [ItsLegendaryCode/PyElite#3]
Howzit, when typing in the document or whatever that row count and column count is incorrectly counting only when i do enter and backspace or something like that

**Comment by ItsLegendaryCode** [comment]
Oh, thanks for telling me about that issue. I will fix it in the near future and as of now I am assuming that this bug is coming from an unhandled event. wx.EVT_TEXT handles all of the updates in the StyledTextCtrl and likewise for it's similar classes.

**Comment by ItsLegendaryCode** [comment]
Also, I am going to double check if you are being legit since I don't have any problems with the line count. I am saying this only to confirm this issue.

**Comment by ItsLegendaryCode** [comment]
Yes, that's the way I had made the line and column counting system work. There's nothing wrong that I see with it, but I don't understand why you have a problem with the fact that it only updates the numerical count when the user has made a keypress.
So, to conclude this issue, I would like to tell you that I don't find this a problem and that other text-editors also use this method. 
If you would like to see more information regarding this topic of line and row count (also the editor component itself), please visit this link:
https://wxpython.org/Phoenix/docs/html/wx.stc.StyledTextCtrl.html
